### ISSUE TITLE
Recent package rename broke plugin discoverability by Vue CLI

### ISSUE THREAD

**Issue by romansp** [deraw/vue-cli-plugin-proxy#3]
**Describe the bug**
Package rename from `@cnamts/vue-cli-plugin-proxy` to `vue-cli-proxy-plugin` broke plugin discoverability by Vue CLI. All Vue CLI plugins should follow naming convention described here: https://cli.vuejs.org/dev-guide/plugin-dev.html#naming-and-discoverability

> `vue-cli-plugin-<name>` or `@scope/vue-cli-plugin-<name>`

**To Reproduce**
1. Install `vue-cli-proxy-plugin`
2. Configure `pluginOptions.proxy` in `vue.config.js`
3. Start development server
4. HPM is missing.

**Expected behavior**
HPM created.

**Comment by deraw** [comment]
**Whoops**

I'm sorry, I absolutely didn't thought about this while doing the modification.

![Box of shame GIF](https://media.giphy.com/media/eP1fobjusSbu/giphy.gif)

**I've published a scoped version with the old package name:** https://www.npmjs.com/package/@deraw/vue-cli-plugin-proxy

_The plugin is again discoverable!_

**Comment by romansp** [comment]
Sorry for posting into closed issue. Is it still possible to update deprecation notice here? https://www.npmjs.com/package/@cnamts/vue-cli-plugin-proxy. So it will produce correct package message in `npm/yarn install`.

`warning @cnamts/vue-cli-plugin-proxy@2.2.1: WARNING: This project has been renamed to vue-cli-proxy-plugin. Install using vue-cli-proxy-plugin instead.`

**Comment by deraw** [comment]
Hi @romansp!

I've updated the deprecation notice on [@cnamts/vue-cli-plugin-proxy](https://www.npmjs.com/package/@cnamts/vue-cli-plugin-proxy) and I added it to [vue-cli-proxy-plugin](https://www.npmjs.com/package/vue-cli-proxy-plugin).

Thank you :slightly_smiling_face:
